//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public DonDatHang()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaDonDatHang { get; set; }
        public int MaNguoiDung { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int ThueSuat { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
