//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CameraShopEntities : DbContext
    {
        public CameraShopEntities()
            : base("name=CameraShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnhSanPham> AnhSanPhams { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public DbSet<ChiTietNhomNguoiDung> ChiTietNhomNguoiDungs { get; set; }
        public DbSet<ChiTietThongSo> ChiTietThongSoes { get; set; }
        public DbSet<DonDatHang> DonDatHangs { get; set; }
        public DbSet<DongSanPham> DongSanPhams { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KhuyenMai> KhuyenMais { get; set; }
        public DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<NhaSanXuat> NhaSanXuats { get; set; }
        public DbSet<NhomNguoiDung> NhomNguoiDungs { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<ThongSo> ThongSoes { get; set; }
        public DbSet<TinTuc> TinTucs { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
    }
}
