//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.DonDatHangs = new HashSet<DonDatHang>();
            this.HoaDons = new HashSet<HoaDon>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
        
        public int MaNguoiDung { get; set; }
        [DisplayName("H? tên")]
        public string TenNguoiDung { get; set; }
        [DisplayName("Gi?i tính")]
        public bool GioiTinh { get; set; }
        [DisplayName("Ð?a ch?")]
        public string DiaChi { get; set; }
        [DisplayName("Ði?n tho?i")]
        public string DienThoai { get; set; }

        [Required(ErrorMessage = "Email Address is required")]
        [DisplayName("Email Address")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",
            ErrorMessage = "Email không h?p l?")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [RegularExpression(@"[0-9]",
            ErrorMessage = "Email không h?p l?")]
        [DisplayName("Nam sinh")]
        public string NamSinh { get; set; }
    
        public virtual ICollection<DonDatHang> DonDatHangs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
