//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomNguoiDung
    {
        public NhomNguoiDung()
        {
            this.ChiTietNhomNguoiDungs = new HashSet<ChiTietNhomNguoiDung>();
        }
    
        public int MaNhomNguoiDung { get; set; }
        public string TenNhomNguoiDung { get; set; }
    
        public virtual ICollection<ChiTietNhomNguoiDung> ChiTietNhomNguoiDungs { get; set; }
    }
}
