//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.ChiTietNhomNguoiDungs = new HashSet<ChiTietNhomNguoiDung>();
            this.TinTucs = new HashSet<TinTuc>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        [DisplayName("Mả người dùng")]
        public int MaNguoiDung { get; set; }


        public System.DateTime NgayTao { get; set; }
        public System.DateTime ThoiGianDangNhap { get; set; }
        [DisplayName("Câu hỏi bảo mật")]
        public string CauHoiBaoMat { get; set; }
        [DisplayName("Trả lời câu hỏi bảo mật")]
        public string TraLoiCauHoiBaoMat { get; set; }
    
        public virtual ICollection<ChiTietNhomNguoiDung> ChiTietNhomNguoiDungs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual ICollection<TinTuc> TinTucs { get; set; }
    }
}
