//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSo
    {
        public ThongSo()
        {
            this.ChiTietThongSoes = new HashSet<ChiTietThongSo>();
        }
    
        public int MaThongSo { get; set; }
        public string TenThongSo { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual ICollection<ChiTietThongSo> ChiTietThongSoes { get; set; }
    }
}
